// This is for laying out various global types to be used all over the site.
// Work in progress.

export const validInputTypes = [
    "button",
    "checkbox",
    "color",
    "date",
    "datetime-local",
    "email",
    "file",
    "hidden",
    "image",
    "month",
    "number",
    "password",
    "radio",
    "range",
    "reset",
    "search",
    "submit",
    "tel",
    "text",
    "time",
    "url",
    "week",
    "select",
    
];

export const fieldTypes = {
	button: "button",
	checkbox: "checkbox",
	color: "color",
	date: "date",
	datetimeLocal: "datetime-local",
	email: "email",
	file: "file",
	hidden: "hidden",
	image: "image",
	month: "month",
	number: "number",
	password: "password",
	radio: "radio",
	range: "range",
	reset: "reset",
	search: "search",
	submit: "submit",
	tel: "tel",
	text: "text",
	time: "time",
	url: "url",
	week: "week",
	select: "select",
};
